AWSTemplateFormatVersion: 2010-09-09

Parameters:
  KeyName:
    Description: Name of an existing EC2 key pair for SSH access to EC2 instances.
    Type: AWS::EC2::KeyPair::KeyName

  SSHLocation:
    Description: The IP address range that can be used to SSH to EC2 instances.
    Type: String
    MinLength: "9"
    MaxLength: "18"
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

  ImageId:
    Description: EC2 Image ID - leave default for latest Amazon Linux 2 image
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64

Resources:
  FinanceVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: FinanceVPC

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ]
      VpcId: !Ref FinanceVPC
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: PrivateSubnet1

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs ]
      VpcId: !Ref FinanceVPC
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Name
          Value: PrivateSubnet2

  PrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ]
      VpcId: !Ref FinanceVPC
      CidrBlock: 10.0.3.0/24
      Tags:
        - Key: Name
          Value: PrivateSubnet3

  PrivateSubnet4:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs ]
      VpcId: !Ref FinanceVPC
      CidrBlock: 10.0.4.0/24
      Tags:
        - Key: Name
          Value: PrivateSubnet4

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ]
      VpcId: !Ref FinanceVPC
      CidrBlock: 10.0.11.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs ]
      VpcId: !Ref FinanceVPC
      CidrBlock: 10.0.12.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet2

  FinanceIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: IGW-Finance

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref FinanceVPC
      InternetGatewayId: !Ref FinanceIGW

  PublicRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref FinanceVPC
      Tags:
        - Key: Name
          Value: FinRT-public

  Route:
    Type: "AWS::EC2::Route"
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref FinanceIGW

  PublicRT1Association:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRT

  PublicRT2Association:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRT

  PrivateRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref FinanceVPC
      Tags:
        - Key: Name
          Value: FinRT-private

  PrivateRT1Association:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRT

  PrivateRT2Association:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRT

  # EC2
  # Secutity Groups
  WebSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and DNS(UDP) access on the inbound port
      GroupName: Finance-WebServer-SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: udp
          FromPort: 53
          ToPort: 53
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Finance-WebServer-SG
      VpcId: !Ref FinanceVPC

  SSHSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and DNS(UDP) access on the inbound port
      GroupName: Finance-SSH-SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
      Tags:
        - Key: Name
          Value: Finance-SSH-SG
      VpcId: !Ref FinanceVPC

  EC2toRDSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow connections to DB from any instances this security group is attached to
      GroupName: EC2-RDS-SG
      Tags:
        - Key: Name
          Value: Finance-EC2-RDS-SG
      VpcId: !Ref FinanceVPC

  EC2toRDSegress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref EC2toRDSSG
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      DestinationSecurityGroupId: !Ref RDStoEC2SG

  RDStoEC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow EC2 instances with specific security groups attached to connect to the database.
      GroupName: RDS-EC2-SG
      Tags:
        - Key: Name
          Value: Finance-RDS-EC2-SG
      VpcId: !Ref FinanceVPC

  RDStoEC2ingress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref RDStoEC2SG
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref EC2toRDSSG

  #FinanceWebServer:
  # Type: AWS::EC2::Instance
  #  Properties:
  #    ImageId: !Ref ImageId
  #    InstanceType: t2.micro
  #    KeyName: !Ref KeyName
  #    SecurityGroupIds:
  #      - !Ref WebSG
  #      - !Ref SSHSG
  #      - !Ref EC2toRDSSG
  #    SubnetId: !Ref PublicSubnet1
  #    Tags:
  #      - Key: Name
  #        Value: Finance-WebServer

  # RDS
  DBSubnetGroup1:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for db-finance
      DBSubnetGroupName: db-finance-subnet-group
      SubnetIds: # Required
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      Tags:
        - Key: Name
          Value: db-finance-subnet-group

  FinanceDB:
    Type: AWS::RDS::DBInstance
    # DeletionPolicy: Retain
    # UpdateReplacePolicy: Retain
    Properties:
      AllocatedStorage: 20
      DBName: finance_db
      VPCSecurityGroups:
        - !Ref RDStoEC2SG
      Engine: postgres

      DBSubnetGroupName: !Ref DBSubnetGroup1
      DBInstanceClass: db.t4g.micro
      DBInstanceIdentifier: db-finance1
      MasterUsername: postgres
      MasterUserPassword: "{{resolve:ssm-secure:/finance/db_pwd}}"
      Tags:
        - Key: Name
          Value: finance_db

  FinanceALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: FinanceALB
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref WebSG
      Tags:
        - Key: Name
          Value: FinanceALB

  FinanceTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: FinanceTargetGroup
      Port: 80
      Protocol: HTTP
      VpcId: !Ref FinanceVPC
      TargetType: instance
      Tags:
        - Key: Name
          Value: FinanceTargetGroup

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref FinanceALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref FinanceTargetGroup

  FinanceASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: FinanceASG
      LaunchConfigurationName: FinanceLaunchConfiguration
      MinSize: 1
      MaxSize: 2
      DesiredCapacity: 1
      VPCZoneIdentifier:
        - !Ref PrivateSubnet3
        - !Ref PrivateSubnet4
      TargetGroupARNs:
        - !Ref FinanceTargetGroup
      Tags:
        - Key: Name
          Value: FinanceASG
          PropagateAtLaunch: true
      HealthCheckGracePeriod: 300

  FinanceLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      LaunchConfigurationName: FinanceLaunchConfiguration
      ImageId: !Ref ImageId
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref WebSG
        - !Ref SSHSG
        - !Ref EC2toRDSSG
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
            VolumeType: gp2
            DeleteOnTermination: true
      AssociatePublicIpAddress: true
